//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCCheckinV3
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckIn
    {
        public int CheckInID { get; set; }
        public Nullable<int> MemberID { get; set; }
        public string FullName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<int> PaidType { get; set; }
        public Nullable<decimal> PaidAmount { get; set; }
        public Nullable<System.DateTime> PaidDate { get; set; }
        public string PaidDesc { get; set; }
        public int DanceType { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<int> ReferredBy { get; set; }
    }
}
