//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCCheckinV3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contestant
    {
        public int ContestantID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string PostalCode { get; set; }
        public string PhoneNumber { get; set; }
        public string EmailName { get; set; }
        public string ContestantNumber { get; set; }
        public string Notes { get; set; }
        public Nullable<int> ClubID { get; set; }
        public Nullable<int> PaidID { get; set; }
    }
}
