//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCCheckinV3
{
    using System;
    using System.Collections.Generic;
    
    public partial class KeyCardTable
    {
        public int PrimaryKey { get; set; }
        public string KeyCardNumber { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public Nullable<int> MemberID { get; set; }
        public Nullable<bool> IsAdmin { get; set; }
        public string MadeAdminBy { get; set; }
    }
}
