//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCCheckinV3
{
    using System;
    using System.Collections.Generic;
    
    public partial class MayBirthday
    {
        public int MemberID { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string HomePhone { get; set; }
        public string WorkPhone { get; set; }
        public string FaxNumber { get; set; }
        public string EmailAddress { get; set; }
        public string Status { get; set; }
        public string DateJoined { get; set; }
        public string Type { get; set; }
        public string LastPaid { get; set; }
        public Nullable<decimal> Dues { get; set; }
        public Nullable<System.DateTime> InputDate { get; set; }
        public string MemberStatus { get; set; }
        public string Organization { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<System.DateTime> Anniversary { get; set; }
        public Nullable<double> DataEaseMemberNumber { get; set; }
        public string BirthMonth { get; set; }
        public string BirthDay { get; set; }
        public bool Charter { get; set; }
        public System.DateTime NewMemberDate { get; set; }
        public Nullable<System.DateTime> DateLastUpdated { get; set; }
        public string LastUpdatedBy { get; set; }
        public string Dateadded { get; set; }
        public string AddedBy { get; set; }
        public string Comments { get; set; }
        public string CellPhone { get; set; }
        public bool InvalidAddress { get; set; }
        public bool IsDeleted { get; set; }
        public int ClassID { get; set; }
        public Nullable<bool> isPromoted { get; set; }
        public Nullable<int> currentMonth { get; set; }
    }
}
