//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCCheckinV3
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SCCheckInEntities : DbContext
    {
        public SCCheckInEntities()
            : base("name=SCCheckInEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<CheckIn> CheckIns { get; set; }
        public virtual DbSet<DeletedMember> DeletedMembers { get; set; }
        public virtual DbSet<OKSwingMemberList> OKSwingMemberLists { get; set; }
        public virtual DbSet<password> passwords { get; set; }
        public virtual DbSet<tblFee> tblFees { get; set; }
        public virtual DbSet<VoidedEntry> VoidedEntries { get; set; }
        public virtual DbSet<Contestant> Contestants { get; set; }
        public virtual DbSet<KeyCardTable> KeyCardTables { get; set; }
        public virtual DbSet<Merchandise> Merchandises { get; set; }
    }
}
